name: somers
channels:
  - conda-forge
dependencies:
  - geoalchemy2
  - ipykernel=6
  - owslib
  - pip=24
  - psycopg2-binary
  - python=3
  - sqlalchemy=2
  - matplotlib
  - pandas
  - numpy
  - scipy
  - pip:
      - hydropandas
